repos:
  - repo: local
    hooks:
      - id: increase-version
        name: Increase version
        entry: .venv/bin/python scripts/increase_version.py patch
        language: system
        pass_filenames: false
        skip: "-nobump"