[project]
name = "file-bundler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic-core>=2.31.1",
    "pyperclip>=1.9.0",
    "ruff>=0.9.10",
    "streamlit>=1.43.2",
]
